# Generated by Django 3.1.7 on 2021-04-18 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('Rating', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('CopiesSold', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/store/applications')),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('Rating', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('CopiesSold', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/store/books')),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('Rating', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('CopiesSold', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/store/games')),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('Rating', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('CopiesSold', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/store/movies')),
                ('Trailer', models.FileField(upload_to='')),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.application')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.game')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='Static/store/profilePictures/defaultPic.jpeg', upload_to='Static/store/profilePictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditMemeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Job', models.CharField(max_length=120)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.movie')),
            ],
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.movie')),
            ],
        ),
    ]
